# Generated by Django 4.2.19 on 2025-02-18 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleauth',
            name='expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
