# Generated by Django 4.2.19 on 2025-02-11 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'permissions': (('export_question', 'Can export question'),)},
        ),
    ]
