# Generated by Django 4.2.19 on 2025-02-13 02:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0003_question_quiz'),
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quizz',
            new_name='Quiz',
        ),
    ]
